name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]   # must match ci.yml 'name'
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download CI artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./backend-build

      - name: Set environment variables
        run: |
          echo "PORT=4000" >> $env:GITHUB_ENV
          echo "NODE_ENV=production" >> $env:GITHUB_ENV

      - name: Install dependencies
        run: npm install --production
        working-directory: ./backend-build

      - name: Start application in background
        run: |
          cd backend-build
          Start-Process "node" "dist/index.js" -WindowStyle Hidden
