name: CI Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint --if-present

      - name: Run tests
        run: echo "Skipping tests (none defined)"

      - name: Build project
        run: npm run build

      - name: Upload backend build
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: |
            dist/
            package.json
            package-lock.json
            